# Numpy 基础运算

In [1]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.arange(4)
print(a, b)

[10 20 30 40] [0 1 2 3]


In [2]:
# 减法
c = a - b
print(c)

[10 19 28 37]


In [3]:
# 加法
c = a + b
print(c)

[10 21 32 43]


In [4]:
# 乘法
c = b**2
print(c)

[0 1 4 9]


In [5]:
c = 10*np.sin(a)
#c = 10*np.cos(a)
#c = 10.np.tan(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [6]:
# 判断值
print(b)
print(b<3)

[0 1 2 3]
[ True  True  True False]


# 矩阵的乘法

In [7]:
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape((2, 2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [8]:
c = a*b
c_dot = np.dot(a, b)
print(c)     # 对应的元素逐个相乘
print(c_dot) # 矩阵相乘，第一行×第一列，...

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [9]:
# 与上面的矩阵相乘一样，只是表达方式不一样而已
c_dot_2 = a.dot(b)
print(c_dot_2)

[[2 4]
 [2 3]]


# 矩阵在行列中求和，最大值和最小值

In [10]:
a = np.random.random((2, 4)) # 0-1 的随机数字
print(a)

[[0.27019165 0.52292157 0.84121317 0.1361308 ]
 [0.17327423 0.6953882  0.28158083 0.52724028]]


In [11]:
print(a)
print(np.sum(a)) # 求和
print(np.min(a)) # 求最小
print(np.max(a)) # 求最大

[[0.27019165 0.52292157 0.84121317 0.1361308 ]
 [0.17327423 0.6953882  0.28158083 0.52724028]]
3.4479407220270613
0.13613079527185268
0.8412131689136058


In [12]:
print(np.sum(a, axis=1)) # 在每一行中的求和
print(np.min(a, axis=0)) # 在每一列中寻求最小
print(np.max(a, axis=1)) # 在每一行中寻求最大

[1.77045718 1.67748354]
[0.17327423 0.52292157 0.28158083 0.1361308 ]
[0.84121317 0.6953882 ]
