In [1]:
import numpy as np
A = np.arange(2, 14).reshape((3, 4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [2]:
# 最小值的索引
print(np.argmin(A))

0


In [3]:
# 最大值的索引
print(np.argmax(A))

11


In [4]:
# 全部元素的平均值的4种方法
print(np.mean(A))
print(A.mean())
print(np.average(A))
print(np.median(A))

7.5
7.5
7.5
7.5


In [5]:
# 累加，后一个元素的值等于前面的元素相加
print(np.cumsum(A))

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [6]:
# 累差
print(np.diff(A))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
# 非0
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [8]:
# 逐行进行排序，从小到大
A = np.arange(14, 2, -1).reshape((3, 4))
print(A)
print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [9]:
# 矩阵的反相，两种写法，也叫转置
print(np.transpose(A))
print(A.T) 

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [10]:
# 小于5的数都变成5,大于9的数都变成9，中间的不变
print(np.clip(A, 5, 9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [11]:
# 求平均值，行计算和列计算
print(np.mean(A, axis=1)) # axis=0 列， 1 行

[12.5  8.5  4.5]
