# Numpy的array合并

In [1]:
import numpy as np
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

In [2]:
# 上下合并
C = np.vstack((A, B)) #vertical stack
print(C)
print(A.shape, C.shape)

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)


In [3]:
# 左右合并
D = np.hstack((A, B)) # horizontal stack
print(D)
print(A.shape, D.shape)

[1 1 1 2 2 2]
(3,) (6,)


In [4]:
# 给数列A加了一个维度
print(A[:, np.newaxis])
A = np.array([1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2])[:, np.newaxis]
D = np.hstack((A, B)) # horizontal stack 左右合并
print(D)
print(A.shape, D.shape)

[[1]
 [1]
 [1]]
[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


In [5]:
# 多个array的合并
C = np.concatenate((A, B, B, A), axis=1) # axis=0
print(C)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
