# Numpy的copy和deepcopy

In [1]:
import numpy as np
a = np.arange(4)
print(a)

[0 1 2 3]


In [2]:
b = a
c = a
d = b

In [3]:
# 赋值的时候，a改变后b,c,d的值同时也改变，有点类似c语言的指针操作
a[0] = 11
print(a)
b is a
print(b)

[11  1  2  3]
[11  1  2  3]


In [4]:
print(d)
d is a

[11  1  2  3]


True

In [5]:
d[1:3] = [22, 33]
print(d)
print(a)

[11 22 33  3]
[11 22 33  3]


In [6]:
# 要想实现改变a的值而不改变其他参数的值，就需要使用copy的方法，类似c语言的memcpy()
b = a.copy() # deep copy
print(b)

[11 22 33  3]


In [7]:
a[3] = 44
print(a)
print(b)

[11 22 33 44]
[11 22 33  3]
